In [3]:
# Importowanie bibliotek

import numpy as np             
import pandas as pd

# Reshape

In [2]:
A = np.arange(12)               # tworzy tablicę NumPy z liczbami od 0 do 11
A                               # wyświetla zawartość tablicy A
A.shape                         # pokazuje kształt tablicy (12 elementów w 1 wymiarze)

(12,)

In [4]:
s = pd.Series(A.tolist())       # konwersja tablicy NumPy na listę i utworzenie obiektu Series
s.iloc[1]                       # pobranie elementu o indeksie 1 (drugi element serii)

np.int64(1)

In [7]:
s                               # wyświetlenie całej serii pandas

0      0
1      1
2      2
3      3
4      4
5      5
6      6
7      7
8      8
9      9
10    10
11    11
dtype: int64

Jedną z najczęściej używanych funkcji w Numpy jest reshape(), która nadaje nowy kształt tablicy bez zmiany jej danych. Kiedy używasz reshape(-1, 1), prosisz numpy o zmianę kształtu tablicy z 1 kolumną i tyloma wierszami, ile potrzeba, aby pomieścić dane. Wynikiem tej operacji będzie tablica 2D o kształcie (n, 1), gdzie n to liczba elementów w oryginalnej tablicy.

In [8]:
C = A.reshape(-1, 1)            # zmiana kształtu tablicy na kolumnę (12 wierszy, 1 kolumna)
C                               # wyświetlenie tablicy C
C.shape                         # sprawdzenie nowego kształtu tablicy C

(12, 1)

reshape(1, -1) przekształca tablicę z 1 wierszem i tyloma kolumnami, ile potrzeba, aby pomieścić dane. Wynikiem tej operacji będzie tablica 2D o kształcie (1, n), gdzie n to liczba elementów w oryginalnej tablicy.

In [9]:
B = A.reshape(1, -1)            # zmiana kształtu tablicy na wiersz (1 wiersz, 12 kolumn)
B                               # wyświetlenie tablicy B

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]])

Kluczową różnicą między reshape(-1, 1) i reshape(1, -1) jest kształt wynikowej tablicy. reshape(-1, 1) skutkuje tablicą z pojedynczą kolumną i wieloma wierszami (wektor kolumn), podczas gdy reshape(1, -1) skutkuje tablicą z pojedynczym wierszem i wieloma kolumnami (wektor wierszy).

In [10]:
D = A.reshape(3, 4)             # zmiana kształtu tablicy na macierz 3x4
D                               # wyświetlenie macierzy D

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

# Wybór wierszy i kolumn

In [23]:
# zaczytanie danych z pliku CSV.
data = pd.read_csv('https://s3-eu-west-1.amazonaws.com/shanebucket/downloads/uk-500.csv')

In [24]:
data.shape        # zwraca kształt obiektu data: (liczba_wierszy, liczba_kolumn)

(500, 11)

In [25]:
data.head(5)      # wyświetla pierwsze 5 wierszy obiektu data

,first_name,last_name,company_name,address,city,county,postal,phone1,phone2,email,web
0,Aleshia,Tomkiewicz,Alan D Rosenburg Cpa Pc,14 Taylor St,St. Stephens Ward,Kent,CT2 7PP,01835-703597,01944-369967,atomkiewicz@hotmail.com,http://www.alandrosenburgcpapc.co.uk
1,Evan,Zigomalas,Cap Gemini America,5 Binney St,Abbey Ward,Buckinghamshire,HP11 2AX,01937-864715,01714-737668,evan.zigomalas@gmail.com,http://www.capgeminiamerica.co.uk
2,France,Andrade,"Elliott, John W Esq",8 Moor Place,East Southbourne and Tuckton W,Bournemouth,BH6 3BE,01347-368222,01935-821636,france.andrade@hotmail.com,http://www.elliottjohnwesq.co.uk
3,Ulysses,Mcwalters,"Mcmahan, Ben L",505 Exeter Rd,Hawerby cum Beesby,Lincolnshire,DN36 5RP,01912-771311,01302-601380,ulysses@hotmail.com,http://www.mcmahanbenl.co.uk
4,Tyisha,Veness,Champagne Room,5396 Forth Street,Greets Green and Lyng Ward,West Midlands,B70 9DT,01547-429341,01290-367248,tyisha.veness@hotmail.com,http://www.champagneroom.co.uk

In [26]:
# Wybór pojedynczego wiersza z wykorzystaniem  iloc i DataFrame

data.iloc[0] #pierwszy wiersz (Aleshia Tomkiewicz) - Zwróc uwagę na typ danych.

first_name                                   Aleshia
last_name                                 Tomkiewicz
company_name                 Alan D Rosenburg Cpa Pc
address                                 14 Taylor St
city                               St. Stephens Ward
county                                          Kent
postal                                       CT2 7PP
phone1                                  01835-703597
phone2                                  01944-369967
email                        atomkiewicz@hotmail.com
web             http://www.alandrosenburgcpapc.co.uk
Name: 0, dtype: str

In [27]:
data.iloc[1] # drugi wiersz ramki danych (Evan Zigomalas)

# kolumny:

first_name                                   Evan
last_name                               Zigomalas
company_name                   Cap Gemini America
address                               5 Binney St
city                                   Abbey Ward
county                            Buckinghamshire
postal                                   HP11 2AX
phone1                               01937-864715
phone2                               01714-737668
email                    evan.zigomalas@gmail.com
web             http://www.capgeminiamerica.co.uk
Name: 1, dtype: str

In [28]:
data.iloc[-1] # Ostatni wiersz ramki danych (Mi Richan)

first_name                                               Mi
last_name                                            Richan
company_name                 Nelson Wright Haworth Golf Crs
address                                     6 Norwood Grove
city                                      Tanworth-in-Arden
county                                         Warwickshire
postal                                              B94 5RZ
phone1                                         01451-785624
phone2                                         01202-738406
email                                        mi@hotmail.com
web             http://www.nelsonwrighthaworthgolfcrs.co.uk
Name: 499, dtype: str

In [29]:
data.iloc[:,0] # pierwsza kolumna ramki danych (first_name)

0        Aleshia
1           Evan
2         France
3        Ulysses
4         Tyisha
         ...
495        Avery
496         Reid
497    Charlette
498    Celestina
499           Mi
Name: first_name, Length: 500, dtype: str

In [30]:
data.iloc[:,1] # druga kolumna ramki danych(last_name)

0      Tomkiewicz
1       Zigomalas
2         Andrade
3       Mcwalters
4          Veness
          ...
495          Veit
496       Euresti
497      Brenning
498         Keeny
499        Richan
Name: last_name, Length: 500, dtype: str

In [31]:
data.iloc[:,-1] # ostatnia kolumna ramki danych (id)

0             http://www.alandrosenburgcpapc.co.uk
1                http://www.capgeminiamerica.co.uk
2                 http://www.elliottjohnwesq.co.uk
3                     http://www.mcmahanbenl.co.uk
4                   http://www.champagneroom.co.uk
                          ...
495      http://www.plazagourmetdelicatessen.co.uk
496             http://www.fitzgeraldedwardj.co.uk
497               http://www.fureyassociates.co.uk
498         http://www.bfgfederalcreditunion.co.uk
499    http://www.nelsonwrighthaworthgolfcrs.co.uk
Name: web, Length: 500, dtype: str

In [33]:
data['id'] = [np.random.randint(0,1000) for x in range(data.shape[0])]
#dodanie losowej wartości całkowitej na końcu danych

In [34]:
data.shape

(500, 12)

In [35]:
data.iloc[:,-1] # ostatnia kolumna ramki danych (id)

0      156
1       57
2      583
3      617
4      667
      ...
495    353
496    365
497    469
498    406
499    207
Name: id, Length: 500, dtype: int64

In [36]:
# Wybór wielu wierszy i kolumn przy użyciu iloc i DataFrame
data.iloc[0:5] # 5 pierwszych wierszy

,first_name,last_name,company_name,address,city,county,postal,phone1,phone2,email,web,id
0,Aleshia,Tomkiewicz,Alan D Rosenburg Cpa Pc,14 Taylor St,St. Stephens Ward,Kent,CT2 7PP,01835-703597,01944-369967,atomkiewicz@hotmail.com,http://www.alandrosenburgcpapc.co.uk,156
1,Evan,Zigomalas,Cap Gemini America,5 Binney St,Abbey Ward,Buckinghamshire,HP11 2AX,01937-864715,01714-737668,evan.zigomalas@gmail.com,http://www.capgeminiamerica.co.uk,57
2,France,Andrade,"Elliott, John W Esq",8 Moor Place,East Southbourne and Tuckton W,Bournemouth,BH6 3BE,01347-368222,01935-821636,france.andrade@hotmail.com,http://www.elliottjohnwesq.co.uk,583
3,Ulysses,Mcwalters,"Mcmahan, Ben L",505 Exeter Rd,Hawerby cum Beesby,Lincolnshire,DN36 5RP,01912-771311,01302-601380,ulysses@hotmail.com,http://www.mcmahanbenl.co.uk,617
4,Tyisha,Veness,Champagne Room,5396 Forth Street,Greets Green and Lyng Ward,West Midlands,B70 9DT,01547-429341,01290-367248,tyisha.veness@hotmail.com,http://www.champagneroom.co.uk,667

In [37]:
data.iloc[:, 0:2] # pierwsze dwie kolumny ramki danych ze wszystkimi wierszami

    first_name   last_name
0      Aleshia  Tomkiewicz
1         Evan   Zigomalas
2       France     Andrade
3      Ulysses   Mcwalters
4       Tyisha      Veness
..         ...         ...
495      Avery        Veit
496       Reid     Euresti
497  Charlette    Brenning
498  Celestina       Keeny
499         Mi      Richan

[500 rows x 2 columns]

In [38]:
data.iloc[[0,3,6,24], [0,5,6]] # 1., 4., 7., 25. wiersz + 1., 6., 7. kolumna.

   first_name        county    postal
0     Aleshia          Kent   CT2 7PP
3     Ulysses  Lincolnshire  DN36 5RP
6        Marg   Southampton  SO14 3TY
24       Tess   West Sussex  PO19 1RH

In [39]:
data.iloc[0:5, 5:8] # pierwszych 5 wierszy i 5, 6, 7 kolumn ramki danych (powiat -> telefon1).

            county    postal        phone1
0             Kent   CT2 7PP  01835-703597
1  Buckinghamshire  HP11 2AX  01937-864715
2      Bournemouth   BH6 3BE  01347-368222
3     Lincolnshire  DN36 5RP  01912-771311
4    West Midlands   B70 9DT  01547-429341

# Macierze / Podmacierze

In [11]:
A=np.arange(25)                 # tworzy tablicę NumPy z liczbami od 0 do 24
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [12]:
B=A.reshape(5,5)
B

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [14]:
C=B[0,:2]
C

array([0, 1])

In [15]:
D=B[0, :]
D

array([0, 1, 2, 3, 4])

In [16]:
E=B[:2, :2]
E

array([[0, 1],
       [5, 6]])

In [17]:
F=B[:3,:3]
F

array([[ 0,  1,  2],
       [ 5,  6,  7],
       [10, 11, 12]])

In [18]:
G=B[1:3,:4]
G

array([[ 5,  6,  7,  8],
       [10, 11, 12, 13]])

In [19]:
T=B[2:4,:4]
T

array([[10, 11, 12, 13],
       [15, 16, 17, 18]])

In [20]:
S=B[2:4,3:5]
S

array([[13, 14],
       [18, 19]])

In [21]:
U=B[3:4,4:5]
U

array([[19]])

In [22]:
a = np.array(B[3:4,4:5])
print(a.item())

19